// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PS57xRSguNJ9xrdLE7DhiXoQK0xOweg',
    appId: '1:137920926530:web:af7044b012136feed22edb',
    messagingSenderId: '137920926530',
    projectId: 'food-delivery-71441',
    authDomain: 'food-delivery-71441.firebaseapp.com',
    storageBucket: 'food-delivery-71441.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3VdCKz7Ves6mj7KLzTPt8vIqDZO-Sfs',
    appId: '1:137920926530:android:b3840d23b9ff2c2cd22edb',
    messagingSenderId: '137920926530',
    projectId: 'food-delivery-71441',
    storageBucket: 'food-delivery-71441.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT2RMrGLKBb9RPYATfMoPdDmu9NDq5fmY',
    appId: '1:137920926530:ios:bf272c3f11801181d22edb',
    messagingSenderId: '137920926530',
    projectId: 'food-delivery-71441',
    storageBucket: 'food-delivery-71441.appspot.com',
    iosBundleId: 'com.example.ninjaDelivery',
  );
}
